# Generated by Django 6.0.4 on 2026-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('revenue_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('competition', models.CharField(max_length=100)),
                ('home_win_pct', models.FloatField()),
                ('draw_pct', models.FloatField()),
                ('away_win_pct', models.FloatField()),
                ('predicted_score', models.CharField(max_length=10)),
                ('confidence', models.IntegerField()),
                ('ai_insight', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
